spring:
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: @spring.datasource.driver-class-name@

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  servlet:
    session:
      timeout: 60m
      cookie:
        name: SESSION_COOKIE
        http-only: true
        secure: true
