spring:
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driver-class-name: @spring.datasource.driver-class-name@
  mail:
    host: @spring.mail.host@
    port: @spring.mail.port@
    username: @spring.mail.username@
    password: @spring.mail.password@
    properties:
      transport:
        protocol: smtp
      smtp:
        ssl:
          enable: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            trust: @spring.mail.properties.mail.smtp.ssl.trust@


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: cc/nyanyanya/backend/common/util/type_handler


server:
  servlet:
    session:
      timeout: 60m
      cookie:
        name: cookieId
        http-only: true
        secure: true
        same-site: lax
